# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WV1UB1loK34qAU3t3hVuS62YqjcEhyau
"""

import math

def pythagoras(a,b):
  c=math.sqrt(a**2+b**2)
  return c

def circle(r):
  area=math.pi*r**2
  return area
